apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ywonchae1/teamsoccer-server
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-configmap
            - secretRef:
                name: server-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
#  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: server